### ISSUE TITLE
Namepsace resource should have a "name" attribute

### ISSUE THREAD

**Issue by andrewrynhard** [terraform-providers/terraform-provider-kubernetes#15]
Without this, we are forced to use `depends_on` for any resources that require the namespace. For example, I want to create a namespace then reference that namespace and create a secret in it. Also, it is not very DRY to update the namespace name in places that depend on it.

**Comment by radeksimko** [comment]
Hi @andrewrynhard 
the [`name` argument](https://www.terraform.io/docs/providers/kubernetes/r/namespace.html#name) (which is also exported attribute, like all other arguments) is part of the `metadata` block.
you can reference the namespace like this:

```hcl
resource "kubernetes_namespace" "example" {
  metadata {
    name = "terraform-example-namespace"
  }
}

resource "kubernetes_config_map" "example" {
  metadata {
    name = "my-config"
    namespace = "${kubernetes_namespace.example.metadata.0.name}"
  }

  data {
    api_host = "myhost:443"
    db_host  = "dbhost:5432"
  }
}
```

I admit the `0` index isn't exactly intuitive, but that's given by the current limitation of Terraform's core/schema. We have some long-term plans for addressing that, so that users could eventually reference such nested field like `${kubernetes_namespace.example.metadata.name}` which would probably make more sense.

I think you shouldn't need to use `depends_on` anywhere in the K8S provider.

I'm going to close this issue as I believe there is nothing to do in the codebase, but do let me know if I this helps or if I misunderstood your question.

Thanks.
