### ISSUE TITLE
Ability to deploy CRD's

### ISSUE THREAD

**Issue by lawrencegripper** [terraform-providers/terraform-provider-kubernetes#183]
As much of the Kubernetes world moves to using CRD's is the provider planning to support a CRD resource?

cc: @scottguymer

**Comment by bukzor** [comment]
Please may we have a response to this question?

**Comment by glesperance** [comment]
Any updates on this?

**Comment by HipsterZipster** [comment]
Any updates @alexsomesan? Istio and others require this

**Comment by lesv** [comment]
It's difficult to install istio & knative.  Istio works w/ Helm, so that can be done, though difficult as one needs to first install the CRD's, wait for them to become stable, then install real Istio.

For kNative, [install](https://knative.dev/docs/install/knative-with-any-k8s/) requires using kubectl apply <[url](https://github.com/knative/serving/releases)>.  Then updating some [installed resources](#221).  Then if you want a few preinstalled things, use `kubectl apply` to install some [non-standard resources](https://github.com/knative/serving/blob/master/docs/spec/normative_examples.md).  For kNative, since it's a big deal, one can create its own provider, but as this becomes a standard, it's going to create a situation that doesn't scale.

I don't know if you have any plans, but as a thought, it might make sense to have resource that triggers from a file or url, and if that file's hash, or URL address changes, remove the old if present, and applies the new.  (for big multi-resource things like kNative).

For individual custom resources, it would be nice to have a data that returns them as a string (probably JSON), with enough tools to extract things from them.  And resources that can detect changes on an input string and either apply (if new), patch (if changed), or delete / apply (if the user asks for that).

**Comment by orefalo** [comment]
same issue here. using tf to deploy arangodb operators. next, is to provision resources tied to the operator nomenclature. those can't be deployed with the current provide features.

operators are becoming more and more common in k8s world.   openfaas also comes with its own operator.

**Comment by lawrencegripper** [comment]
I built something out here: https://github.com/lawrencegripper/terraform-provider-kubernetes-yaml

It's now being supported on a fork which may be of use to people.

**Comment by orefalo** [comment]
Thank you @lawrencegripper found it a few days ago. Works like a charm! Cheers

**Comment by ryuheechul** [comment]
I found a workaround that works for me.
1. [helm provider](https://www.terraform.io/docs/providers/helm/index.html) can help you install whatever yaml that Kubernetes will accept.
2. you can create simple chart holds your crds as template yaml in your terraform code repository.
3. install it via `helm_release` pointing at that repository

And of course this method is not only for CRDs but for any yaml manifests.

**Comment by digitalkaoz** [comment]
@ryuheechul any example?

i tried it, but the helm provider complained about the char not be gzipped (its a plain yaml file)

**Comment by rubenv** [comment]
Here's two:

https://github.com/rubenv/helm-cert-manager-crds
https://github.com/rubenv/helm-cert-manager-issuers-letsencrypt

**Comment by ryuheechul** [comment]
@digitalkaoz If you made a chart locally, you should use relative path in [chart](https://www.terraform.io/docs/providers/helm/r/release.html#chart)

**Comment by Sytten** [comment]
Relates to https://github.com/terraform-providers/terraform-provider-kubernetes/issues/215

**Comment by aareet** [comment]
Closing this in favour of https://github.com/terraform-providers/terraform-provider-kubernetes/issues/215 since we are tracking this issue there.
