### ISSUE TITLE
ContainerPort: ForceNew

### ISSUE THREAD

**Issue by roidelapluie** [terraform-providers/terraform-provider-kubernetes#20]
Hi,

In kubernetes pods, we can not update a container port. Is there a reason not to have set ForceNew on those schema fields?

Thanks.

**Comment by radeksimko** [comment]
Hi @roidelapluie 
there's a reason. We did discuss this during the initial implementation of `kubernetes_pod`.

It was more-or-less deliberate decision because there are part of the schema shared between `pod` and `replication_controller`. Some fields are updatable in the context of the second resource.

That said I agree it would be useful to reflect these differences in the schema while still taking benefits of shared schema. I will have a think about it.

**Comment by radeksimko** [comment]
I didn't realize until today the update was actually implemented in a way that it ignores most fields 🙈 I must have missed that during code review. That puts this issue into a significantly different light.

Relabelling as `bug` and will have a look at solution 🔜

**Comment by roidelapluie** [comment]
that was quick 🎉
