### ISSUE TITLE
Feature Request: CronJob resource.

### ISSUE THREAD

**Issue by hden** [terraform-providers/terraform-provider-kubernetes#212]
### References
- https://kubernetes.io/docs/concepts/workloads/controllers/cron-jobs/

**Comment by kilhage** [comment]
+1

**Comment by peterver** [comment]
+1 but i'm guessing since even in k8s 1.12 it's in v1beta1 this is a nogo for now ?

**Comment by jhoblitt** [comment]
It looks like `Job` has been out of beta for awhile.  The oldest I checked was `1.10`.  Unfortunately, as of `1.13`, `CronJob` is still beta :https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.13/#cronjob-v1beta1-batch

However, since the the api version is in the resource definition, it doesn't seem like using the beta api is really all that risky. @alexsomesan could we revisit the no `v1beta1` policy?

**Comment by RobMaskell** [comment]
Or maybe consider a beta provider that has these beta resources in it, would probably be useful for the GCP provider too given the long beta cycle of some google cloud resources?

**Comment by luizferreira094** [comment]
+1

**Comment by dustinblackman** [comment]
It looks like this PR could use some love. https://github.com/terraform-providers/terraform-provider-kubernetes/pull/411

**Comment by tuckerconnelly** [comment]
@alexsomesan I'm sure you're super busy, and looks like you recently got back from vacation. Just curious on ETA, excited to use this (:

**Comment by tdmalone** [comment]
This is now merged / can probably be closed! :tada:
https://github.com/terraform-providers/terraform-provider-kubernetes/pull/411
