### ISSUE TITLE
Feature request for Kubernetes pods

### ISSUE THREAD

**Issue by MaximF** [terraform-providers/terraform-provider-kubernetes#31]
### Terraform Version
Terraform v0.9.11

### Explanation
Basing on [official documentation](https://www.terraform.io/docs/providers/kubernetes/index.html) there is no way to configure pods inside kubernetes cluster.
However, there is [community-based plugin](https://github.com/maxmanuylov/terraform-provider-kubernetes) doing the missing functionality.

It would be great, if Terraform could provision and manage pods natively.
Thank you!

### References
https://github.com/maxmanuylov/terraform-provider-kubernetes

**Comment by radeksimko** [comment]
Hi @MaximF 
`kubernetes_pod` probably slipped through the cracks of Changelogs somewhere between 0.9 and 0.10 (provider split), but it is supported:

https://github.com/hashicorp/terraform/pull/13571
Docs: https://github.com/terraform-providers/terraform-provider-kubernetes/blob/master/website/docs/r/pod.html.markdown

It's available in the latest `0.10beta` which should automatically download the latest K8S provider (0.1.1).

Sorry for the confusion caused by the website, it will be updated as part of the upcoming major release (0.10.0) soon. The good news is that as providers are now versioned & released separately we don't need to rely on the release cycle of the main TF project, after 0.10 is out.

**Comment by MaximF** [comment]
Awesome, thank you @radeksimko!
