### ISSUE TITLE
kubernetes_namespace fails to destroy; stuck in Terminating state

### ISSUE THREAD

**Issue by appnojag** [terraform-providers/terraform-provider-kubernetes#335]
### Terraform Version

 - v0.11.11

### Affected Resource(s)

 - kubernetes_namespace

### Terraform Configuration Files
```hcl

resource "kubernetes_namespace" "foo" {
  metadata {
    name = "foo"
  }
}

```

### Expected Behavior

Kubernetes namespace gets deleted [within hardcoded 5m timeout] during terraform destroy.

### Actual Behaviour

Kubernetes namespace is stuck in Terminating state; terraform destroy fails.

### Important Factoids

 - Google Kubernetes Engine 1.11.7-gke.4

### Steps to Reproduce

1. `terraform destroy`

### References

- GH-60807

**Comment by appnojag** [comment]
https://github.com/kubernetes/kubernetes/issues/60807

**Comment by markeissler** [comment]
The following reply in that issue thread suggests it's a terraform problem that's causing this, related to the order in which resources are destroyed:

https://github.com/kubernetes/kubernetes/issues/60807#issuecomment-463764193

**Comment by alexsomesan** [comment]
@appnojag Can you provide of log of the destroy operation with TF_LOG=TRACE environment variable set? This will allow us to trace the communication between Terraform and the K8s API.
If this is cause by the problem described in the Kubernetes thread mentioned above, then there isn’t a whole lot Terraform can do.

**Comment by gertjangaillet** [comment]
@appnojag - can you check if the configurable timeout resolves your issue?

**Comment by alexsomesan** [comment]
This issue is easily reproduced on vanilla Kubernetes by configuring a namespace with a malfunctioning finalizer. This is not something that can be mitigated by the provider and as such there's not much we can do here but fail the destroy in the event of timeout.

Can you confirm if setting the `Delete` timeout on the namespace resource works for you as described?

**Comment by chrisrot** [comment]
@alexsomesan Can elaoborate how to avoid a malfunctioning finalizer?
I have created the namespace like this:
```
resource "kubernetes_namespace" "foo" {
  metadata {
    annotations = {
      name = "foo"
    }
    name = "foo"
  }
}
```

**Comment by dan-barrett** [comment]
@chrisrot, I was seeing the same issue you are. I'm realizing that this is an issue with the kubernetes APIs rather than a specific kubernetes_namespace you've deployed to.

Try running this: `kubectl api-resources`

If everything is okay, you should simply see a full list of the Kubernetes APIs. However, I saw this error at the bottom:

```
error: unable to retrieve the complete list of server APIs: compose.docker.com/v1alpha3: the server is currently unable to handle the request, compose.docker.com/v1beta1: the server is currently unable to handle the request, compose.docker.com/v1beta2: the server is currently unable to handle the request
```

According to [this comment](https://github.com/kubernetes/kubernetes/issues/60807#issuecomment-429754733) Kubernetes will rightfully _not_ delete a namespace if one if its APIs is unreachable.

So you need to fix your Kubernetes API before deleting the namespace. I simply rebooted my Docker for Desktop Kubernetes cluster and that worked!

**Comment by alexsomesan** [comment]
This is not something that can be controlled on the client side of Kubernetes (where this provider finds itself). There isn't any action we plan to take on the provider side.

Further details are available in the upstream Kubernetes issue: https://github.com/kubernetes/kubernetes/issues/77086
