### ISSUE TITLE
Documentation ".id" output undocumented

### ISSUE THREAD

**Issue by jeffb4** [terraform-providers/terraform-provider-kubernetes#554]
In the web documentation for kubernetes provider resources, for instance https://www.terraform.io/docs/providers/kubernetes/r/namespace.html the fact that the `.id` output/attribute is equivalent to `name` is never documented. That would be super useful to terraform noobs trying to easily reference resources in a way that makes dependency mapping easy.

**Comment by alexsomesan** [comment]
The `id` attribute is an internal attribute that Terraform uses to correlate a resource's state between state file and remote system. It's only requirement is that it has to identify the resource uniquely.

However, it not guaranteed to be equivalent to the resource `name`. In fact, for resources that are namespaced, it's actually a combination of the values of `namespace` and `name`.

We don't encourage access of ID in any user scenarios because it's treated as internal.
