### ISSUE TITLE
Allow setting automountServiceAccountToken on replication controller

### ISSUE THREAD

**Issue by calind** [terraform-providers/terraform-provider-kubernetes#56]
Currently the the `kubernetes_replication_controller` creates the spec with `automountServiceAccountToken` set to `false`. This means that the service account credentials selected by `service_account_name` are not available in the container.

https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#use-the-default-service-account-to-access-the-api-server

**Comment by sl1pm4t** [comment]
@calind @radeksimko I have a fix for this in my fork, and will send over a PR.

**Comment by radeksimko** [comment]
Hi @calind 
see more detailed explanation of why we don't support this field and why it's hardcoded to `false` at https://github.com/terraform-providers/terraform-provider-kubernetes/issues/38#issuecomment-318450761

The service account does expose [`default_secret_name`](https://www.terraform.io/docs/providers/kubernetes/r/service_account.html#default_secret_name) in case you want to replicate the behaviour.

@sl1pm4t I'm fairly confident you can't make RC/Pod/ServiceAccount creation idempotent with `automountServiceAccountToken` - try creating the resource and then running plan after a few seconds when the token was attached.

Let me know if the explanation makes sense and whether we can close this.

**Comment by sl1pm4t** [comment]
Hi @radeksimko - I disagree that we can't make the creation idempotent. As discussed in PR #57 if we ignore `volumes` / `volumeMounts` with a name matching `default-token-*` on read then there won't be a diff. I'm sure something similar could be done for a ServiceAccount.
Sure it's not perfectly elegant, and has a small gotcha, but I think it's a better option than not allowing automountServiceAccountToken, and breaking expected + documented behaviour of Kubernetes.

**Comment by radeksimko** [comment]
Hi @sl1pm4t 
it's unfortunately not that simple due to the way Token Controller works.

Basically the fix you're proposing only deals with situation where there's no `service_account` specified, so the default one is used, hence `default-token-` naming scheme is used.
The secret name (which is then used for the volume/mount name) is generated from service account name, see https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/serviceaccount/tokens_controller.go#L384

So we'd have to ignore all of `*-token-*` which would be IMO a bit too aggressive.

I have opened https://github.com/kubernetes/kubernetes/issues/51328 to track the upstream feature request as discussed earlier.

Are you happy for me to close this issue & related PR #57 and move the discussion over to https://github.com/kubernetes/kubernetes/issues/51328 ?

Just to clarify - I really want to give users the chance to specify this field and use this handy functionality, but I'd like to do so with minimal (ideally no) disruption for anyone, that's why I believe upstream changes should take place first.

Let me know if that makes sense.

**Comment by sl1pm4t** [comment]
Ok I see your point @radeksimko - thanks for taking the time to explain.

**Comment by ccope** [comment]
@radeksimko do you have a clear path forward after the discussion on https://github.com/kubernetes/kubernetes/issues/51328 ? I just spent the better part of an hour figuring out why the service account secret wasn't getting populated in my container :-)

**Comment by radeksimko** [comment]
@ccope The plan is to add validation to prevent people from using `kubernetes_secret` to manage service tokens and then add filtering based on type of the secret.

**Comment by victorsmirnov** [comment]
[How should I put 'secrets' to my POD the right way?](https://stackoverflow.com/questions/48666147/issues-with-kubernetes-api-secrets-not-mounted-in-the-pod-when-using-terraform-k)

I suggest to put an example to the documentation with simple explanation how this should be done. May be I'm missing something but after reading all these discussions I still do not understand how I should do this.

**Comment by moritzheiber** [comment]
A short term remedy for this issue would be to have a data source read the secret name of the service account, which you could then use to mount the token into your pod. It's cumbersome and I'd prefer a better solution, but for now this is what we're doing using a combination of `kubectl` and `terraform` with a variable :frowning_face:

**Comment by schuettecarsten** [comment]
When will this be released?

**Comment by moritzheiber** [comment]
According to the [Changelog](https://github.com/terraform-providers/terraform-provider-kubernetes/blob/master/CHANGELOG.md#180-july-02-2019) this was released in July :smiley:

**Comment by aareet** [comment]
This should be resolved -> https://github.com/terraform-providers/terraform-provider-kubernetes/issues/56#issuecomment-524802194. Please reopen if that's not the case.
