### ISSUE TITLE
kubernetes.io/dockercfg type as docker secret for image_pull_secrets is not working

### ISSUE THREAD

**Issue by odedpriva** [terraform-providers/terraform-provider-kubernetes#79]
I set up a docker secret using : 
```
resource "kubernetes_secret" "docker" {
  metadata {
    name = "docker-cfg"
  }

  data {
    ".dockercfg" = "${file("/Users/odedpriva/.docker/config.json")}"
  }

  type = "kubernetes.io/dockercfg"
}
```
trying to use it in pod resource returns an `ErrImagePull` error

```
resource "kubernetes_pod" "debug2" {
  count = "${var.services["debug"] ? 1 : 0}"

  metadata {
    name = "debug2"

    labels = {
      service = "debug"
    }
  }

  spec {
    image_pull_secrets = {
      name = "docker-cfg"
    }

    container {
      name  = "net-tools"
      image = "${var.debug["net-tools-image"]}:${var.debug["net-tools-tag"]}"
    }
  }
}
```

when creating this secret manually using k8s api 
```
kubectl create secret docker-registry regsecret --docker-server=index.docker.io --docker-username=*** --docker-password=*** --docker-email=***@****
```
and referencing this secret in pod resource worked like a charm.

What am I doing wrong ? 

```
local git:(master) ✗ ter version
Terraform v0.10.7
```

**Comment by peckeltw** [comment]
@radeksimko  please try:
`type = "kubernetes.io/dockerconfigjson"`
instead of 
`type = "kubernetes.io/dockercfg"`

Terraform's [documentation](https://www.terraform.io/docs/providers/kubernetes/r/secret.html) seems to be wrong, but please have a look at Kubernetes' [documentation](https://kubernetes.io/docs/concepts/containers/images/#specifying-imagepullsecrets-on-a-pod).
